"use client";
import {useEffect,useState} from "react";
import {Package,Plus,Search,Calculator,Check,X,Trash2,Layers3,Database,Settings2} from "lucide-react";
import {migrateIngredient,lineCost,recalculateRecipes} from "../lib/costing.mjs";
const API="https://rough-salad-1a98.yosefahmed1952004.workers.dev/api/management/state";
const uid=()=>crypto.randomUUID();
const blank=()=>({id:uid(),name:"",unit:"جرام",pricePerUnit:""});
const money=n=>new Intl.NumberFormat("ar-EG",{style:"currency",currency:"EGP"}).format(n||0);
export default function Page(){
 const [tab,setTab]=useState("ingredients"),[items,setItems]=useState([]),[draft,setDraft]=useState([]),[recipes,setRecipes]=useState([]),[q,setQ]=useState(""),[recipe,setRecipe]=useState(null),[loaded,setLoaded]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{(async()=>{try{
  const response=await fetch(API);if(!response.ok)throw Error("تعذر تحميل البيانات. أعد تحميل الصفحة للمحاولة.");const data=await response.json();
  const next=(data.initialized?data.ingredients||[]:JSON.parse(localStorage.getItem("em_ingredients")||"[]")).map(migrateIngredient);
  const products=data.initialized?data.recipes||[]:JSON.parse(localStorage.getItem("em_recipes")||"[]");
  setItems(next);setDraft([...next,blank()]);setRecipes(recalculateRecipes(products,next));setLoaded(true);
 }catch(error){setNotice("تعذر تحميل البيانات. أعد تحميل الصفحة للمحاولة.")}})()},[]);
 const persist=async(next,products=recipes)=>{setSaving(true);setNotice("");try{
  const updated=recalculateRecipes(products,next);const response=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ingredients:next,recipes:updated})});
  if(!response.ok)throw Error("تعذر الحفظ. تعديلاتك ما زالت موجودة؛ حاول مرة أخرى.");setItems(next);setRecipes(updated);setNotice("تم الحفظ");return true;
 }catch(error){setNotice(error.message);return false}finally{setSaving(false)}};
 const patch=(id,key,value)=>setDraft(rows=>{const next=rows.map(row=>row.id===id?{...row,[key]:value}:row);if(next.at(-1).id===id)next.push(blank());return next});
 const saveIngredients=async()=>{
  const entered=draft.filter(row=>row.name.trim()||row.pricePerUnit!=="");
  if(entered.some(row=>!row.name.trim()||row.pricePerUnit===""||!Number.isFinite(Number(row.pricePerUnit))||Number(row.pricePerUnit)<0)){setNotice("أدخل اسم المنتج وسعرًا صحيحًا لا يقل عن صفر لكل صف.");return}
  const next=entered.map(row=>({...row,name:row.name.trim(),pricePerUnit:Number(row.pricePerUnit),migrationNeedsReview:false}));
  if(await persist(next))setDraft([...next,blank()]);
 };
 return <div className="shell"><aside><div className="brand"><div className="mark">M</div><div><b>EL MOHANDES</b><span>MANAGEMENT</span></div></div><nav><button className={tab==="ingredients"?"active":""} onClick={()=>setTab("ingredients")}><Package/>الخامات</button><button className={tab==="recipes"?"active":""} onClick={()=>setTab("recipes")}><Calculator/>تكلفة المنتجات</button><button disabled><Layers3/>التحضيرات <small>قريبًا</small></button><button disabled><Database/>المخزون <small>قريبًا</small></button></nav><div className="asideFoot"><Settings2/> El Mohandes Management <span>Costing v1</span></div></aside><main>
 {notice&&<p role="status">{notice}</p>}{!loaded?<p>{notice?"لم يتم تحميل البيانات.":"جارٍ تحميل البيانات…"}</p>:tab==="ingredients"?<section>
 <header><div><span className="eyebrow">COSTING / BULK ENTRY</span><h1>الخامات</h1><p>اكتب مباشرة في الجدول. يظهر صف جديد تلقائيًا عند الإدخال.</p></div><button className="primary" disabled={saving} onClick={saveIngredients}><Check/>{saving?"جارٍ الحفظ…":"حفظ الكل"}</button></header>
 <div className="toolbar"><div className="search"><Search/><input aria-label="البحث عن منتج" value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث باسم المنتج…"/></div><div className="count">إدخال وتعديل مباشر</div></div>
 {draft.some(row=>row.migrationNeedsReview)&&<p>بعض الأسعار القديمة تحتاج مراجعة. أدخل السعر لكل وحدة في الخانات الفارغة ثم احفظ.</p>}
 <fieldset disabled={saving} className="gridFieldset"><div className="tableWrap"><table className="bulk"><thead><tr><th>اسم المنتج</th><th>الوحدة</th><th>السعر لكل وحدة</th></tr></thead><tbody>{draft.filter(row=>!row.name||row.name.includes(q)).map(row=><tr key={row.id} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();e.currentTarget.nextElementSibling?.querySelector("input")?.focus()}}}>
 <td><input aria-label="اسم المنتج" value={row.name} onChange={e=>patch(row.id,"name",e.target.value)}/></td><td><select aria-label="الوحدة" value={row.unit} onChange={e=>patch(row.id,"unit",e.target.value)}>{["جرام","مل","قطعة"].map(unit=><option key={unit}>{unit}</option>)}</select></td><td><input aria-label="السعر لكل وحدة" type="number" min="0" step="any" value={row.pricePerUnit} onChange={e=>patch(row.id,"pricePerUnit",e.target.value)}/></td></tr>)}</tbody></table></div></fieldset>
 <p className="gridHelp">مثال: سجق — جرام — 0.20 جنيه. تكلفة 150 جرام = 30 جنيه.</p></section>:<section><header><div><span className="eyebrow">COSTING / PRODUCTS</span><h1>تكلفة المنتجات</h1><p>تكلفة الخامة = الكمية × السعر لكل وحدة.</p></div><button className="primary" onClick={()=>setRecipe({id:uid(),name:"",category:"",price:"",lines:[]})}><Plus/>منتج جديد</button></header><div className="cards">{recipes.map(product=>{const cost=product.lines.reduce((sum,line)=>sum+lineCost(line,items),0);return <article className="product" key={product.id} onClick={()=>setRecipe(structuredClone(product))}><span>{product.category||"منتج"}</span><h3>{product.name}</h3><div><b>{money(cost)}</b><small>التكلفة الحالية</small></div><div><b>{money(product.price)}</b><small>سعر البيع</small></div><footer>Food cost {product.price?(cost/product.price*100).toFixed(1):0}%</footer></article>})}{!recipes.length&&<div className="empty">ابدأ بإضافة أول منتج</div>}</div></section>}</main>
 {recipe&&<RecipeModal value={recipe} items={items} saving={saving} onClose={()=>setRecipe(null)} onSave={async value=>{if(await persist(items,recipes.some(r=>r.id===value.id)?recipes.map(r=>r.id===value.id?value:r):[value,...recipes]))setRecipe(null)}}/>}</div>
}
function RecipeModal({value,items,saving,onClose,onSave}){
 const [v,setV]=useState(value);
 const patch=(id,key,value)=>setV(current=>({...current,lines:current.lines.map(line=>line.id===id?{...line,[key]:value}:line)}));
 const add=type=>setV({...v,lines:[...v.lines,type==="ingredient"?{id:uid(),type,ingredientId:items[0]?.id||"",qty:""}:{id:uid(),type,name:"",cost:""}]});
 const total=v.lines.reduce((sum,line)=>sum+lineCost(line,items),0);
 const valid=v.name.trim()&&v.lines.every(line=>line.type==="ingredient"?items.some(i=>i.id===line.ingredientId)&&line.qty!==""&&Number.isFinite(Number(line.qty))&&Number(line.qty)>=0:line.cost!==""&&Number.isFinite(Number(line.cost))&&Number(line.cost)>=0);
 return <div className="overlay"><div className="modal wide"><div className="modalHead"><h2>تكلفة المنتج</h2><button className="icon" disabled={saving} onClick={onClose} aria-label="إغلاق"><X/></button></div><fieldset disabled={saving} className="gridFieldset"><div className="formGrid"><label>اسم المنتج<input value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>القسم<input value={v.category} onChange={e=>setV({...v,category:e.target.value})}/></label><label>سعر البيع<input type="number" min="0" step="any" value={v.price} onChange={e=>setV({...v,price:e.target.value})}/></label></div><div className="subhead"><h3>مكونات التكلفة</h3><div className="actions"><button className="secondary" disabled={!items.length} onClick={()=>add("ingredient")}><Plus/>خامة</button><button className="secondary" onClick={()=>add("direct")}><Plus/>تكلفة مباشرة</button></div></div>
 <div className="lines">{v.lines.map(line=><div className="line" key={line.id}><span className="badge">{line.type==="ingredient"?"خامة":"مباشر"}</span>{line.type==="ingredient"?<><select aria-label="الخامة" value={line.ingredientId} onChange={e=>patch(line.id,"ingredientId",e.target.value)}><option value="" disabled>اختر خامة</option>{items.map(item=><option key={item.id} value={item.id}>{item.name} ({item.unit})</option>)}</select><label>الكمية ({items.find(i=>i.id===line.ingredientId)?.unit||"غير متاحة"})<input aria-label="الكمية" type="number" min="0" step="any" value={line.qty} onChange={e=>patch(line.id,"qty",e.target.value)}/></label></>:<><input aria-label="اسم التكلفة المباشرة" value={line.name} onChange={e=>patch(line.id,"name",e.target.value)}/><input aria-label="التكلفة المباشرة" type="number" min="0" step="any" value={line.cost} onChange={e=>patch(line.id,"cost",e.target.value)}/></>}<b>{money(lineCost(line,items))}</b><button className="trash" aria-label="حذف المكون" onClick={()=>setV({...v,lines:v.lines.filter(l=>l.id!==line.id)})}><Trash2/></button></div>)}</div><div className="summary"><span>إجمالي تكلفة المنتج</span><strong>{money(total)}</strong><span>Food Cost</span><strong>{v.price?(total/v.price*100).toFixed(1):0}%</strong></div><div className="modalActions"><button className="secondary" onClick={onClose}>إلغاء</button><button className="primary" disabled={!valid} onClick={()=>onSave(v)}>حفظ المنتج</button></div></fieldset></div></div>
}
